import type { Metadata } from "next";
import "./globals.css";
import "./reset.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="bottom-center"
          toastOptions={{
            duration: 2000,
            style: {
              fontFamily: "Pretendard, -apple-system",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
